export default {
    productsALLData: [
        {
            id: 'dance-1',
            category: 'dance-events',
            title: 'RETROPARTY',
            date: '21.03.2024',
            url: './img/content/dance-1.png',
        },
        {
            id: 'dance-2',
            category: 'dance-events',
            title: 'Дискотека 90-х 2000-х',
            date: '25.05.2024',
            url: './img/content/dance-2.png',
        },
        {
            id: 'dance-3',
            category: 'dance-events',
            title: 'DiscoВЕСНА',
            date: '18.05.2024',
            url: './img/content/dance-3.png',
        },
        {
            id: 'dance-4',
            category: 'dance-events',
            title: 'SLAM Dance',
            date: '28.04.2024',
            url: './img/content/dance-4.png',
        },
        {
            id: 'movie-1',
            category: 'movie',
            title: 'Hot Wheels. Вперёд!',
            date: '10.05.2024',
            url: './img/content/movie-1.png',
        },
        {
            id: 'movie-2',
            category: 'movie',
            title: 'Любви не бывает?',
            date: '01.05.2024',
            url: './img/content/movie-2.png',
        },
        {
            id: 'movie-3',
            category: 'movie',
            title: 'Приключение панды',
            date: '25.04.2024',
            url: './img/content/movie-3.png',
        },
        {
            id: 'movie-4',
            category: 'movie',
            title: 'Как я встретил её маму!',
            date: '08.05.2024',
            url: './img/content/movie-4.png',
        },
        {
            id: 'theater-1',
            category: 'theater-performances',
            title: 'Мой дедушка был вишней',
            date: '15.11.2024',
            url: './img/content/theater-1.png',
        },
        {
            id: 'theater-2',
            category: 'theater-performances',
            title: 'Кто боится Вирджинии Вулф?',
            date: '26.07.2024',
            url: './img/content/theater-2.png',
        },
        {
            id: 'theater-3',
            category: 'theater-performances',
            title: 'Нос майора Ковалёва',
            date: '05.06.2024',
            url: './img/content/theater-3.png',
        },
        {
            id: 'theater-4',
            category: 'theater-performances',
            title: 'Кто это сделал?',
            date: '23.05.2024',
            url: './img/content/theater-4.png',
        },
        {
            id: 'museums-1',
            category: 'museums-exhibitions',
            title: 'Ночь музеев. ЖД Вокзал',
            date: '17.05.2024',
            url: './img/content/museums-1.png',
        },
        {
            id: 'museums-2',
            category: 'museums-exhibitions',
            title: 'GameExpo & Unicon 2024',
            date: '13.09.2024',
            url: './img/content/museums-2.png',
        },
        {
            id: 'museums-3',
            category: 'museums-exhibitions',
            title: 'Гомель. Иллюзия ретро',
            date: '22.11.2024',
        },
        {
            id: 'museums-4',
            category: 'museums-exhibitions',
            title: 'KUKLA',
            date: '02.10.2024',
        },
    ],
};
